### PR TITLE
auth_rules for CANdy Test environment.

### PR DESCRIPTION
**Pull request by WadeBarnes**
Signed-off-by: Wade Barnes <wade@neoterictech.ca>

### CODE REVIEW

**Comment by dave-promulgare** [comment]
I have reviewed this change and have some points and questions.

Notable entries:

- These rules change the number of Trustees required to create an Endorser (Add Endorser) from 1 to 2.  I think this is a good choice for security.
- The rules for changing any role to Author do not include a new_value in the command.  I assume that this is the correct syntax.
- The command to change Endorser to Author only requires 1 Trustee the description states that 2 should be required.  I could see an argument for either way.
- We are not using Rich Schema.  This rule should be changed to FORBIDDEN to reflect that.
- The add revocation registry entry has an extraneous OR condition that should be fixed.  
- Is there a way to have the  owner of the REVOC_REG_ENTRY be the user who created the CLAIM_DEF?

**Comment by WadeBarnes** [comment]
> * The rules for changing any role to Author do not include a new_value in the command.  I assume that this is the correct syntax.
- Correct
> * The command to change Endorser to Author only requires 1 Trustee the description states that 2 should be required.  I could see an argument for either way.
- Fixed.  It was meant to be 2.
> * We are not using Rich Schema.  This rule should be changed to FORBIDDEN to reflect that.
- Disabled Rich Schema use.
> * The add revocation registry entry has an extraneous OR condition that should be fixed.
- Fixed.
> * Is there a way to have the  owner of the REVOC_REG_ENTRY be the user who created the CLAIM_DEF?
- I'm not sure whether this is possible without a code change.  I'd have to dig into the code to see if "owner" in the context of a REVOC_REG_ENTRY refers to the CLAIM_DEF.

**Comment by swcurran** [comment]
There is some owner definitions here: https://github.com/hyperledger/indy-node/blob/main/docs/source/auth_rules.md#who-is-owner

It says for a REV_REG_ENTRY for ADD (and EDIT), the OWNER is the owner of the REV_REG_DEF, so that is what is being asked for here. What doesn't appear to be possible is the creation of the REV_REG_DEF by the OWNER of the CRED_DEF -- for some reason OWNER is "N/A" in that case.

**Comment by WadeBarnes** [comment]
> There is some owner definitions here: https://github.com/hyperledger/indy-node/blob/main/docs/source/auth_rules.md#who-is-owner
> 
> It says for a REV_REG_ENTRY for ADD (and EDIT), the OWNER is the owner of the REV_REG_DEF, so that is what is being asked for here. What doesn't appear to be possible is the creation of the REV_REG_DEF by the OWNER of the CRED_DEF -- for some reason OWNER is "N/A" in that case.

Which could mean there is no owner context set for the REVOC_REG_DEF Add operation, but it would be good to confirm what is required to define one (i.e. whether or not a code change is required).

**Comment by WadeBarnes** [comment]
@SylvainMartel, These auth_rules have already been applied to CANdy-Test.  Can they be merged into the repo please?

**Pull request merged**
